(() => {
  //If you want to add more images, add the link name and URL image URL in the array list below.
  const images_list = [
    {
      url: "images/taman-bermain.jpg",
      alt: "",
      name: "Taman Bermain",
      link: "",
    },
    {
      url: "images/jogging-track.jpg",
      alt: "",
      name: "Jogging Track",
      link: "",
    },
    {
      url: "images/kolam-renang.jpg",
      alt: "",
      name: "Kolam Renang",
      link: "",
    },
    {
      url: "images/fitness-center.jpg",
      alt: "",
      name: "Fitness Center",
      link: "",
    },
  ];

  // generated by https://www.html-code-generator.com/html/image-slideshow-generator
  let slider_id = document.querySelector("#fasilitas-slider-1");

  // append all images
  let dots_div = "";
  let images_div = "";
  for (let i = 0; i < images_list.length; i++) {
    // if no link without href="" tag
    let href =
      images_list[i].link == "" ? "" : ' href="' + images_list[i].link + '"';
    images_div +=
      "<a" +
      href +
      ' class="fasilitas-slides animated"' +
      (i === 0 ? ' style="display:flex"' : "") +
      ">" +
      '<span class="fasilitas-slide-number">' +
      (i + 1) +
      "/" +
      images_list.length +
      "</span>" +
      '<img src="' +
      images_list[i].url +
      '" alt="' +
      images_list[i].name +
      '">' +
      '<span class="fasilitas-slide-text">' +
      images_list[i].name +
      "</span>" +
      "</a>";
    dots_div +=
      '<a href="#" class="fasilitas-slide-dot' +
      (i === 0 ? " dot-active" : "") +
      '" data-id="' +
      i +
      '"></a>';
  }
  slider_id.querySelector(".fasilitas-slider-body").innerHTML = images_div;
  slider_id.querySelector(".fasilitas-slide-dot-control").innerHTML = dots_div;

  let slide_index = 0;

  const images = slider_id.querySelectorAll(".fasilitas-slides");
  const dots = slider_id.querySelectorAll(".fasilitas-slide-dot");
  const showSlides = () => {
    if (slide_index > images.length - 1) {
      slide_index = 0;
    }
    if (slide_index < 0) {
      slide_index = images.length - 1;
    }
    for (let i = 0; i < images.length; i++) {
      images[i].style.display = "none";
      dots[i].classList.remove("dot-active");
      if (i == slide_index) {
        images[i].style.display = "flex";
        dots[i].classList.add("dot-active");
      }
    }
  };

  const dot_click = (event) => {
    event.preventDefault();
    slide_index = event.target.dataset.id;
    showSlides();
  };

  for (let i = 0; i < dots.length; i++) {
    dots[i].addEventListener("click", dot_click, false);
  }
  // auto play
  setInterval(() => {
    slide_index++;
    showSlides();
  }, 10000);
})();
